package de.leonso.xfl;

public enum ParseType {NULL, ALPHANUM, STRING, STRING_START,
	PARENTHESES_START, PARENTHESES_END, SEMIKOLON,
	OPERATOR, OPERATOR_SEARCH,
	LIST_SUBSCRIPT_START, LIST_SUBSCRIPT_END}

